import streamlit as st
import time
from orchestrator import ScrappyOrchestrator

# Page configuration for the Scrappy Market UI
st.set_page_config(page_title="Scrappy Market AI", layout="wide")

# Initialize the Orchestrator as a session state singleton
if "orchestrator" not in st.session_state:
    st.session_state.orchestrator = ScrappyOrchestrator()

# Initialize Session State for multiple chats if not present
if "all_chats" not in st.session_state:
    st.session_state.all_chats = {"Chat 1": []}
if "current_chat" not in st.session_state:
    st.session_state.current_chat = "Chat 1"

# --- SIDEBAR: Chat History & Management ---
with st.sidebar:
    st.title("Welcome")
    
    # New Chat Button logic
    if st.button("New Chat", use_container_width=True):
        new_chat_id = f"Chat {len(st.session_state.all_chats) + 1}"
        st.session_state.all_chats[new_chat_id] = []
        st.session_state.current_chat = new_chat_id
        st.rerun()

    st.divider()
    st.subheader("Recent Chats")
    
    # Chat Selection Menu
    for chat_name in list(st.session_state.all_chats.keys()):
        if st.button(chat_name, key=chat_name, use_container_width=True):
            st.session_state.current_chat = chat_name
            st.rerun()

# --- CACHING STRATEGY TO PREVENT TIMEOUTS ---
# Prevents UI refresh issues when Ollama takes time to respond
@st.cache_data(show_spinner=False, ttl=1800)
def get_investigation_results(user_query):
    """Triggers the LangGraph workflow and caches the result"""
    return st.session_state.orchestrator.investigate(question=user_query)

# --- MAIN INTERFACE ---
st.title("Scrappy Market")
st.caption(f"Currently viewing: **{st.session_state.current_chat}**")

# Display historical messages for the selected chat
for message in st.session_state.all_chats[st.session_state.current_chat]:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# User Input Section
if prompt := st.chat_input("Enter your business question here..."):
    # Add user message to session history
    st.session_state.all_chats[st.session_state.current_chat].append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        # Real-time status container for agent progression
        with st.status("🔍 AI Agents are investigating...", expanded=False) as status:
            st.write("Phase 1: Analyzing intent and business metrics...")
            
            # Executing the cached agent workflow
            final_state = get_investigation_results(prompt)
            
            # Display Intent Agent findings
            st.write(f"✔ **Intent:** {final_state.get('question_type', 'Classified')}")
            
            st.write("Phase 2: Generating investigation plan...")
            # Iterating through steps generated by the Planner Agent
            steps = final_state.get('investigation_steps', [])
            for s in steps:
                st.write(f"  └─ Action: {s.get('action')}")
            
            st.write("Phase 3: Building optimized SQL queries...")
            st.write(f"✔ **Status:** {len(final_state.get('generated_queries', []))} queries created")
            
            status.update(label="Investigation Complete!", state="complete", expanded=False)

        # --- RESULTS DISPLAY ---
        st.markdown("### 📊 SQL Generated")
        queries = final_state.get('generated_queries', [])
        if queries:
            for q in queries:
                st.write(q.get('label','No Label'))
                st.code(q.get('query', '-- No query available'), language="sql")
        
        

        st.markdown("### 📊 Summary")
        st.info(f"Focus areas identified: {', '.join(final_state.get('focus_areas', []))}")
        st.write(final_state.get('summary'))

    # Save assistant response summary to history
    st.session_state.all_chats[st.session_state.current_chat].append({
        "role": "assistant", 
        "content": "Investigation finished. SQL queries are ready for review."
    })